/*
@author ranjanmanish
this simple java code takes the two text files generated by python code to
create a unique user list.
PS: did not do in python as it was easy to code in java for me
*/
import java.io.*;
import java.util.*;

class UniqueUser{
  public static void main(String args[]){
    String fileName = "/home/manish/fall2015/RA/DrunkTweetAnalysis/all_user.txt";
    Set<String> uniqUser = new HashSet<String>();
    
    try{

          //Create object of FileReader
          FileReader inputFile = new FileReader(fileName);

          //Instantiate the BufferedReader Class
          BufferedReader bufferReader = new BufferedReader(inputFile);

          //Variable to hold the one line data
          String line;

          // Read file line by line and print on the console
          while ((line = bufferReader.readLine()) != null)   {
            //System.out.println(line);
            // Data format 1100          SimonGire
            String[] noandUser = line.split("\\s+");
            uniqUser.add(noandUser[1]);
          }
          for (String s: uniqUser){
            System.out.println(s);
          }
          //Close the buffer reader
          bufferReader.close();
       }catch(Exception e){
          System.out.println("Error while reading file line by line:" + e.getMessage());
       }
  }

}
